### ISSUE TITLE
Discovery Form - Remove 'checkmark' from behind Discovery Form option checkboxes 

### ISSUE THREAD

**Issue by spalko** [CCI-Studios/sRubber-Duck#13]
![sduck5](https://cloud.githubusercontent.com/assets/692091/26762871/6e8405be-4917-11e7-9eac-8c67a3c5b056.png)

**Comment by ianfader** [comment]
Still showing on these:

![screen shot 2017-06-08 at 3 27 54 pm](https://user-images.githubusercontent.com/8989188/26947026-32bc084c-4c5f-11e7-8f6f-8812ee66b9cc.png)
