### ISSUE TITLE
Responsive - Header - Keep the text size the same as desktop

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/sRubber-Duck#40]

**Comment by ianfader** [comment]
Text is overlapping.

![unnamed](https://user-images.githubusercontent.com/8989188/27052909-5e633632-4f89-11e7-8531-31e6aeec99d6.jpg)

**Comment by ccmorris** [comment]
This new problem was only on your phone eh. Try this one again. I tried a thing.
