### ISSUE TITLE
Discovery Form and Contact Forms - Add reCAPTCHA

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/sRubber-Duck#46]

**Comment by ianfader** [comment]
Getting a fatal error message when pressing submit with nothing filled out in the form.

**Comment by ccmorris** [comment]
I think this is fixed by #47

**Comment by ianfader** [comment]
Discovery form page is saying: To use reCAPTCHA you must get an API key from https://www.google.com/recaptcha/admin

![screen shot 2017-06-13 at 9 15 38 am](https://user-images.githubusercontent.com/8989188/27084179-ec7b5884-5018-11e7-8d5f-ed9aa1c64fad.png)

**Comment by ccmorris** [comment]
oops the old captcha field didn't delete properly
