### ISSUE TITLE
reCAPTCHA - please make consistent

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/sRubber-Duck#47]
Preferably the "I'm not a robot"

![screen shot 2017-06-12 at 4 10 43 pm](https://user-images.githubusercontent.com/8989188/27053016-d09cb110-4f89-11e7-8096-ee43625f1668.png)

**Comment by ianfader** [comment]
Change to the invisible one

**Comment by ccmorris** [comment]
replaced with the invisible recaptcha. it does show an icon on the bottom left. it's not completely invisible!
