### ISSUE TITLE
Consultation Form - Email 

### ISSUE THREAD

**Issue by leverscci** [CCI-Studios/sRubber-Duck#49]
When submitting a free consultation form (Name, number, email) on the main page and at the bottom of all other pages, no email is received at info@srubberduck.com 

Please send all consultation request emails to info@srubberduck.com. 

Google chrome.

**Comment by ccmorris** [comment]
These messages might be going to spam. Please check your spam folder.

**Comment by leverscci** [comment]
Works correctly, thank you
