### ISSUE TITLE
Discovery form - Email

### ISSUE THREAD

**Issue by leverscci** [CCI-Studios/sRubber-Duck#50]
Submitting a discovery form does not send an email to info@srubberduck.com. Submitting it will bring up a message properly saying thank you for submitting, we just do not receive an email to our address. 

Please have all discovery forms sent to info@srubberduck.com. 

Google chrome.

**Comment by ccmorris** [comment]
This form did not have the email message turned on. Please try this again, and check your spam folder as well.

**Comment by leverscci** [comment]
received correctly. Thank you
