### ISSUE TITLE
Discovery form - Changes in the form

### ISSUE THREAD

**Issue by leverscci** [CCI-Studios/sRubber-Duck#54]
Please add fields:
- text fields for:
1. "Contact name" - required
2. "Phone Number"
3. "Email Address" - required

Add option under "have you ever had previous SEO on your site? If so, please check the investment level"
- add clickable option for "No previous SEO"

Add option under "are you doing any other forms of marketing. Check all that apply"
- Text field for option "Other"

**Comment by ianfader** [comment]
Can we add the text field when the user checks "other"?

**Comment by ccmorris** [comment]
Yes. Added text field "Which other forms of marketing are you using?" when you check "Other"
