### ISSUE TITLE
Services - Links that need to be changed 

### ISSUE THREAD

**Issue by leverscci** [CCI-Studios/sRubber-Duck#56]
In Services

You will need the PDFs to upload instead of the current ones. We will send these by email. 

Links that need to be changed

**SEO**
PDF - Make this our own SEO primer, in new tab
(button) Ask us now  > Take instead to the discovery form

**Brand optimization**
(button) I want to optimize my brand now > Take instead to the discovery form

**Web Design**
- PDF - Make this our own SEO primer, in new tab
- (button) Website Packages > Take instead to the discovery form

**Social media services**
- PDF - Make this our own SEO primer, in new tab
- (button) Connect with your customers now > Take instead to the discovery form

**Local buzz**
- PDF - Make this our own SEO primer, in new tab
- (button) Find out more >Take instead to the discovery form

**Website Audit**
- PDF - Make this our own SEO primer, in new tab
- (button) Learn more about the website audit >Take instead to the discovery form

**Pay Per Click**
- PDF - Make this our own SEO primer, in new tab
- (button) Learn more > Take instead to the discovery form

**Online reputation repair**
- PDF - Make this our own SEO primer, in new tab
- (button) Learn more > Take instead to the discovery form

**Comment by ccmorris** [comment]
button links updated. waiting on primer PDFs.

**Comment by ianfader** [comment]
Please add the updated PDFs from the file server:
- [x]  - SEO
- [x]  - Local Buzz
- [x]  - PPC - change button to say "Click to view PPC PDF"
- [x]  - AdWords (goes on same page as PPC) - change button to say "Click to view AdWords PDF"

Please have PPC and Adwords in separate boxes

Please remove PDFs from the following services:
- [x]  - Brand Optimization
- [x]  - Web Design
- [x]  - Social Media Services
- [x]  - Online Reputation Repair
- [x]  - Website Audit
