### ISSUE TITLE
Footer on all pages - change the greenish colour to #2a65b0 hex value

### ISSUE THREAD

**Issue by spalko** [CCI-Studios/sRubber-Duck#6]
![sduck3](https://cloud.githubusercontent.com/assets/692091/26762784/eea29f5a-4915-11e7-9a22-efe78c7dd253.png)

**Comment by ccmorris** [comment]
Please be more specific. Is it the text colours? All of the teal in your screenshot?

**Comment by ianfader** [comment]
All of the teal colour.

**Comment by ccmorris** [comment]
ty
